app = "bitcoin-0-2"
primary_region = "cdg"

[build]

[[services]]
  internal_port = 8333
  protocol = "tcp"

  [[services.ports]]
    port = 8333

  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
